### ISSUE TITLE
webserver wake up time setup  issue

### ISSUE THREAD

**Issue by mrmate2** [mtnbkr88/ESP32CAMRemotePIR#1]
Good day, many thanks for such usefull application.
For testing purposes I am running esp32cam from power adapter, no battery yet.
I am not able to adjust webserver wake up time, its always 99h99m. figures are changing,but immediately they revert to 99h99m
By the way, what is the practical use of such webserver behavior,to save battery power?

**Comment by mtnbkr88** [comment]
Hi mrmate2,
I'm glad you find my application useful. My code is out there as a starting point for anybody to modify to their hearts content. 

I have not had any issues with any of my four ESP32CAM boards keeping the set wake up time. Here are a few things for you to look at. 1) I use Windows 10 and Firefox browser to access my ESP32CAMs. I have not tried any other browsers. If you are not using Firefox, maybe your browser is not communicating the wake up in a way the webserver on the ESP32CAM expects. Are you seeing the confirmation popup that the wake up time was changed and does it have the correct value? 2) The subroutine where this is handled is called settings_handler. Put some Serial.println statements in there to verify the new wake up time info is getting back to the ESP32CAM. 3) Is it saving other values you are setting? 4) On line 93 of the code the default initial value for the wake up time is set to 1300 (1 pm) Pacific Time in the US. Do you see this initial time after a fresh firmware upload? If not, clear the flash to remove any leftovers from other firmware uploads before doing this firmware upload so the default initial values get loaded.  

My ESP32CAMs each run off of one 18650 battery that is charged with a small solar panel and they are placed around my property. They are coded to deep sleep and wake only if the attached PIR detects motion or at the one specified wake up time so I can do maintenance like looking at what it sees or remotely uploading new firmware. This behavior is necessary to save battery power. If you don't need this behavior, change your copy of the code so it never times out to go to deep sleep.

Feel free to download and modify your own copy of this code any way you want, but please don't modify my code here (I'm not sure if you can or can't). I'm using this repository as a place to store my own code and to share it with others who might be interested in a starting point for their projects.

Thanks and good luck.

**Comment by mrmate2** [comment]
Appreciate for Your detailed reply.
As per Your advise, I cleared the flash to remove any leftovers from other firmware uploads before doing this firmware upload so the default initial values get loaded, and now all is fine!!! I can set time for this option without issues.
Would like to ask You additional questions:
1) in what line and which parametr exactly do I have to change in order to set different timezone?
2) )in what line and which parametr exactly do I have to change in order to cancel deepsleep and to enable webserver run constantly?
Many thanks for Your replies and patience.
Best regards from Ukraine.

**Comment by mtnbkr88** [comment]
1) The timezone is set with the TZ_INFO constant on line 42. Since you are in Ukraine I'm going to guess you change "PST8PDT,M3.2.0/2:00:00,M11.1.0/2:00:00" to something like "EET-2EEST,M3.5.0/3:00:00,M10.5.0/4:00:00". 

2) In the loop() subroutine, comment out lines 2752-2754 so do_deep_sleep() is never called.

**Comment by mrmate2** [comment]
Great! code in line 42 changed.
Remaining 1 step for me to be happy,but while compilation I am getting first error:
                               expected unqualified-id befofe "if"
![photo_2020-08-24_21-31-35](https://user-images.githubusercontent.com/40000364/91082687-b1537e80-e651-11ea-9a25-2067ab661ef2.jpg)

PS
Hold on, seems my mistake,:I did not commented line 2754 .
Reflashed the esp32 cam now....
will test result

**Comment by mtnbkr88** [comment]
You commented out only two lines of the if statement. You need to comment out the third line with the curly bracket to hide the whole if statement.

**Comment by mrmate2** [comment]
Yes, You are  right. noticed the same and updated my previous post few minutes fefore Your kind reply.
Now testing how all works.
Many thanks again!! All the best!

**Comment by mrmate2** [comment]
Unfortunately,after modifying timezone settings and disabling deepsleep, all functions are working as usuall, exept photo/video alert on PIR motion detected. It is not a surprise due to :

>  Upon start this sketch will check if start was from a PIR signal or the deep 
 * timer/power on/reset).
 * 
 * If wakeup was from the PIR this sketch will send a remote trigger command to the 
 * remoteTriggerIP then, based on settings, take and email pictures or take and 
 * email a short video. Then it will go into a deep sleep. 
 * If wakeup was from the deep sleep timer/power on/reset then start a web server 
 * for 10 minutes to allow changing configuration settings or update firmware.
 * Then it will go into a deep sleep.

so it means : no deep sleep-no wake up and PIR alert....
Seems I will undo my changes in the code and use original version, as absence of PIR alert makes camera no more usefull as security detection device. 
Luckily, https://github.com/mtnbkr88/ESP32CAMVideoRecorder is nearby!
Apprreciate Your work done, time spent and advices given!

**Comment by mtnbkr88** [comment]
The ESP32CAMRemotePIR code is for an ESP32CAM running off of solar power so it sleeps most of the time. The ESP32CAMVideoRecorder code is for an ESP32CAM that is plugged in all the time, so that is the better choice for you. It's web server will always be on. Don't forget to configure its network, email and timezone info for you and clear your flash before putting this new image on. Note: the ESP32CAMVideoRecorder requires a mini SD card (any size) so it has a place to store pictures and videos. You will be able to view, download or delete these through the web site.
