### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by allbondy** [mtnbkr88/ESP32CAMRemotePIR#7]
it is most like me 
but cant work it out 
help would be greatly appreciated

![remoteepir](https://user-images.githubusercontent.com/5403705/224113457-464b55f3-86f2-4896-87e1-54434de51ecf.png)

**Comment by mtnbkr88** [comment]
ADC2_GPIO12_CHANNEL is defined as part of esp32 library version 1.0.2. In Arduino IDE (I'm using version 1.8.15), go into Tools->Board: "ESP32 Wrover Module"->Boards Manager... . In the search bar at the top, search for esp32. When esp32 library is found, set the version to 1.0.2 then pick Install. This should solve your issue.
