### ISSUE TITLE
Guru Meditation Error: Core  1 panic'ed

### ISSUE THREAD

**Issue by Patsjemoe** [mtnbkr88/ESP32CAMRemotePIR#9]

**Comment by Patsjemoe** [comment]
trying few more things, therefore actually closed

**Comment by mtnbkr88** [comment]
Hi Ludo,

I'm still using Arduino 1.8.15 and board version 1.0.2.
Install the attached EspExceptionDecoder.jar using the instructions below. Paste the backtrace from the error in the tool and it will tell you what line in the code is giving the error and a clue as to why.
    - Create folder C:\Users\Owner\Documents\Arduino\tools\EspExceptionDecoder\tool.
    - Unzip EspExceptionDecoder.zip and place EspExceptionDecoder.jar in the directory create above.
    - Restart Arduino IDE. ESP Exception Decoder can now be found under Tools.

[EspExceptionDecoder.zip](https://github.com/mtnbkr88/ESP32CAMRemotePIR/files/12622438/EspExceptionDecoder.zip)

**Comment by Patsjemoe** [comment]
Hi there,
It's been a while... 😃. Hope you are OK.
I first had put in the back trace, but took it out, because I thought it
was because for whatever reason the board version updated. Went back to a
clean 1.02.
Now I do not get the panic error anymore, but with 1.0.2 waiting in email
picture, and moving to 1.0.5, it says waiting in email picture, failed to
send, end of setup, esp ready, so it goes further.
I can go onto the server.
Trying to figure out why it does not send the mail.... Should  be OK, as I
am running 2 other birdhouses.... But it is not.
Best regards
Ludo


Op vr 15 sep. 2023 20:12 schreef mtnbkr88 ***@***.***>:

**Comment by mtnbkr88** [comment]
Hi Ludo,
When I tried board versions higher than 1.0.2 I got errors so I just stuck with 1.0.2. Your issue is a mystery. Did you try a different board with the exact same code to verify it's not a hardware issue? Did you add any other code that is using up heap? I found that lots of heap needs to be available for network stuff to work. Maybe put some print statements that show the heap before, during, and after the email to see if its a low memory issue.

**Comment by Patsjemoe** [comment]
Looks like 1.05 impacts something...
Have following info , part of your program :
After camera init  Free Heap: 101068
Email picture name is > 2023-09-15_11_54_27.jpg <
 waiting in emailpicture  Heap is: 166636
Failed to send email
 End of setup  Free Heap: 166636
ESP32 Ready! Use 'http://192.x.x.x' to connect

**Comment by mtnbkr88** [comment]
Search for //#define DEBUG_EMAIL_PORT (around line 460 in my copy of the code), uncomment this line (remove two slashes), then recompile and run again. You should see debug info for the sending email part. Hopefully there will be a clue in there as to why the email is failing to send.

**Comment by Patsjemoe** [comment]
Hi,
Thanks for yr suggestion, did not know it was in there .
Connecting: smtp.gmail.com:465
Connecting: smtp.gmail.com:465
Connecting: smtp.gmail.com:465
Connecting: smtp.gmail.com:465
Connecting: smtp.gmail.com:465
Failed to send email
It must have to do with my app password...made a new one, but still a
problem...look further.

Stil not working after a whole day, so any idea is welcome.
Had 2 other birdhouses working, nothing changed, so I am puzzled.
Since I had to change my psw, it also deletes all app psw in Google, so
made new ones..... Surprised that google has no tool to quickly check app
password...

regards
Ludo

**Comment by mtnbkr88** [comment]
Hi Ludo,
Based on your message above it sounds like you are using an app password for sending your email which is what I had to do last year. 

The output you posted shows its failing it's first connection to the gmail server. Look for the below in your code and add the lines with "//*** add for debug" in them to hopefully see why the connection is failing:

#ifdef DEBUG_EMAIL_PORT
  Serial.print(F("Connecting: "));
  Serial.print(host);
  Serial.print(":");
  Serial.println(port);
#endif
  if (!client->connect(host.c_str(), port))
  {
#ifdef DEBUG_EMAIL_PORT                  //*** add for debug
    String buffer = readClient();              //*** add for debug
    Serial.print(F("SERVER->CLIENT: "));  //*** add for debug
    Serial.println(buffer);                        //*** add for debug
#endif                                                 //*** add for debug
    return false;
  }
  String buffer = readClient();

If that doesn't work, to hopefully see what code client->connect(host.c_str(), port) is returning replace:

 if (!client->connect(host.c_str(), port))

with:

 int clientReturnCode;
 clientReturnCode = client->connect(host.c_str(), port));
 Serial.print(F("clientReturnCode: "));
 Serial.println(clientReturnCode);
 if (!clientReturnCode)

Look in https://github.com/espressif/newlib-esp32/blob/master/newlib/libc/include/sys/errno.h
to see what the clientReturnCode means.

I have had the problem where my ESP32 chips have sent too many emails to gmail and they blocked login from my ESP32 thinking it was spam. Waiting a day unblocked the account.


Below are my notes from when I had to switch to using an app password for my esp32 stuff in case it helps.

NOTE: Around 06/07/22 gmail made changes that broke my sendmail stuff. I had to do the
following to create another gmail account and use a 2-factor app password:
- Create another gmail account so if it gets messed up it doesn't screw my normal gmail 
  account.
  - Go to https://www.google.com/gmail/about/.
  - Pick Create an account.
  - First: <private>, Last: ESP32, Username: <private>ESP32@gmail.com, PW: usual
  - Recovery email: <private>@gmail.com, bday, gender
- Create an App Password to use with the new gmail account.
  - Open the google account. https://myaccount.google.com/u/1/?hl=en
    (Make sure its for <private>ESP32@gmail.com and not my other gmail address.
  - In navigation panel, select Security.
  - Under "Signing in to google", select 2-Step Verification->Get started.
  - Follow prompts to complete 2-step verification.
  - Back to google account page, select Security again.
  - Under "Signing in to Google", select App Passwords.
  - Set Selected app to mail, and selected device to Other and set its name to ESP32, 
    Generate. Copy the 16 char password to use as the password later: <app_pw>
- Yay, its working with <private>esp32@gmail.com and the password above. Use these
  for future emails from my esp32 chips.

Good luck!
Ed

**Comment by Patsjemoe** [comment]
Hi,
You showed :
Set Selected app to mail, and selected device to Other and set its name to
ESP32,
I did not see anything to assign to mail, only to delete it.
Will check again...
Not sure how, right click?
Regards
Ludo

Op zo 17 sep. 2023 01:20 schreef mtnbkr88 ***@***.***>:

**Comment by Patsjemoe** [comment]
Hi,
after first replacement : 5x
Connecting: smtp.gmail.com:465
SERVER->CLIENT:

after second replacement (clientReturnCode = client->connect(host.c_str(),
port);
Connecting: smtp.gmail.com:465
clientReturnCode: 0 ---> did not find this code
SERVER->CLIENT:
Regards
Ludo

**Comment by Patsjemoe** [comment]
Hi,
I moved back (again) to 1.0.2 , and now it works again....
I am not sure what is happening, but will just be glad it works.
Still, In Gmail, I cannot select App PSW in security google login, but need
to go to 2 step verification and then go to
app.....but cannot select /assign the password to some application....I do
not have a dropdown menu. Try google to get response on this...
Thanks again for your attention and help.
regards
Ludo

**Comment by mtnbkr88** [comment]
Glad it works again. My notes are from over a year ago so its likely Google change something since then. FYI - A return code of 0 means there was no error and it should have worked correctly.

Good luck,
Ed
